### PR TITLE
build: add hashes to requirements.txt

### PR DESCRIPTION
**Pull request by thiagowfx**
How: `pip install hashin`, `cd tests/`, `hashin anys pytest [...]`.

Fixed: #1182

### CODE REVIEW

**Comment by thiagowfx** [comment]
> ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    Deprecated~=1.2 from https://files.pythonhosted.org/packages/20/8d/778b7d51b981a96554f29136cd[59](https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/6152293015/job/16694169144?pr=1283#step:9:60)ca7880bf58094338085bcf2a979a0e6a/Deprecated-1.2.14-py2.py3-none-any.whl (from anys==0.2.1->-r tests/requirements.txt (line 1))

In order to submit this, first we'll need to submit a PR upstream (https://github.com/jwodder/anys) to change [`setup.cfg`](https://github.com/jwodder/anys/blob/master/setup.cfg).

**Comment by thiagowfx** [comment]
Sent https://github.com/jwodder/anys/pull/3 upstream.

**Comment by thiagowfx** [comment]
Now it's blocked on https://github.com/jwodder/anys/pull/4, which IMHO is even better :D

**Comment by thiagowfx** [comment]
```
25hCollecting typing-extensions>=4.1.0 (from mypy==1.5.1->-r tests/requirements.txt (line 4))
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=4.1.0 from https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl (from mypy==1.5.1->-r tests/requirements.txt (line 4))
```

This one will be harder...https://github.com/python/mypy/blob/master/pyproject.toml:

**Review by jrandolf — APPROVED** [review]

**Comment by thiagowfx** [comment]
I will try another approach: https://github.com/GoogleChromeLabs/chromium-bidi/pull/1480.

**Pull request closed without merging**
