### PR TITLE
ci(pre-commit): enforce conventionalcommit.org

### PR DESCRIPTION
**Pull request by thiagowfx**

### CODE REVIEW

**Review by jrandolf — APPROVED** [review]

**Comment by thiagowfx** [comment]
I'll go ahead with this with one disclaimer: if it makes the workflow too annoying then it will be reverted.

**Comment by OrKoN** [comment]
does it validate the PR title (final merge commit)?

**Comment by thiagowfx** [comment]
This is validation for the local workflow only (commit-msg instead of pre-commit).
It is intended to remember people to prepend prefixes right away.

It knows nothing about GitHub PRs. pre-commit.com cannot help here.

I saw there's another presubmit check that was added recently - I suppose that one covers the PR title, at least when it's initially created?

**Comment by OrKoN** [comment]
Yes, that covers the PR and strictly speaking any commit message can be used in the branches

**Pull request merged**
