### PR TITLE
TS: ensure all local imports have a .js suffix

### PR DESCRIPTION
**Pull request by thiagowfx**

### CODE REVIEW

**Comment by thiagowfx** [comment]
Alex, IIRC you mentioned it once in a past PR that this should be the case, but please correct me if I remember it wrongly.

**Review by OrKoN — APPROVED** [review]

**Comment by thiagowfx** [comment]
Ah, this should have been merged against main, not against the parent branch. It’s really inconvenient to work with multiple children PRs on GitHub.

**Comment by OrKoN** [comment]
Ah I overlooked it. I think this kind of change should not be made dependent on other branch. Should we revert-reland?

**Comment by thiagowfx** [comment]
Not your fault, i could easily have done the same mistake. Yes we should revert. I can do that.

**Pull request merged**
