### PR TITLE
Use deep serialization

### PR DESCRIPTION
**Pull request by sadym-chromium**
* Bump DevTools protocol dependency to unlock deep serialization
* Use deep serialization
* Update + add e2e tests

### CODE REVIEW

**Comment by thiagowfx** [comment]
The original is https://github.com/GoogleChromeLabs/chromium-bidi/pull/668

**Review by thiagowfx — APPROVED** [review]

**Comment by thiagowfx** [comment]
Approving to unblock

**Comment by sadym-chromium** [comment]
> This may break puppeteer. c.f. #670 and cc @Lightning00Blade

Postponing till Puppeteer 114 version cut.

**Comment by sadym-chromium** [comment]
bump CI

**Review by OrKoN — APPROVED** [review]

**Comment by sadym-chromium** [comment]
As discussed offline, not blocked by Puppeteer release anymore

**Pull request merged**
