### PR TITLE
build: disable the minification

### PR DESCRIPTION
**Pull request by nechaev-chromium**
Chromium third party policies disallow any minified code: [adding_to_third_party.md](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/adding_to_third_party.md#Binaries_obfuscated-or-minified-code).
This code disables the code minification that was introduced earlier.

### CODE REVIEW

**Comment by sadym-chromium** [comment]
@Lightning00Blade do we still need `plugin-terser` package?

**Comment by Lightning00Blade** [comment]
No we do not need it. It was only used here. 
So we should remove it from the `package.json` (both `terser` and `@rollup/plugin-terser`).

**Comment by nechaev-chromium** [comment]
> No we do not need it. It was only used here. So we should remove it from the `package.json` (both `terser` and `@rollup/plugin-terser`).

Done!

**Review by Lightning00Blade — APPROVED** [review]
LGTM + side effect of this we should get better stack traces locally and on GitHub Actions if something fails.

**Pull request merged**
