### PR TITLE
improve pytest ergonomics with native assertions

### PR DESCRIPTION
**Pull request by thiagowfx**
- introduce and use `anys` pytest matchers
- use native assert comparisons instead of custom `recursive_compare`
- use type comparisons instead of `any_value` in some circumstances

Reference: https://github.com/jwodder/anys

As of now:

image

With Anys, but without icdiff:

image

With this PR (=Anys + icdiff):

image

### CODE REVIEW

**Comment by sadym-chromium** [comment]
My concerns: 
1. `any_value` seems to be more readable when the specific value is not important for the test.
2. Is it feasible to add the same `anys` to WPT? I find it useful having not that diverse infra for e2e and WPT.

I assume `dict1 <= dict2` would work as well?

**Comment by thiagowfx** [comment]
> 1. `any_value` seems to be more readable when the specific value is not important for the test.

We could still use an `any_value` equivalent, not a problem.

> 2/ Is it feasible to add the same anys to WPT? I find it useful having not that diverse infra for e2e and WPT.

I see. Possibly, but it would require extra investigation. Will defer it to another time then.

> I assume assert `dict1 <= dict2` would work as well?

What do you expect that comparison to do? (And how is it done today?)

**Comment by thiagowfx** [comment]
I'll archive/simmer this, and only extract the `icdiff` part to another PR.

**Comment by thiagowfx** [comment]
> 1. any_value seems to be more readable when the specific value is not important for the test.

Done. Replace with `from unittest.mock import ANY`.

> 2. Is it feasible to add the same anys to WPT? I find it useful having not that diverse infra for e2e and WPT.

Yes. I looked into wpt tests today and it should be feasible.

**Review by sadym-chromium — APPROVED** [review]

**Pull request merged**
