### PR TITLE
update @puppeteer/browsers to 0.5.0

### PR DESCRIPTION
**Pull request by thiagowfx**

### CODE REVIEW

**Comment by sadym-chromium** [comment]
could you please check why the tests are failing?

**Comment by thiagowfx** [comment]
```
 puppeteer:browsers:launcher Trying to kill 23912 +1s
  puppeteer:browsers:launcher Browser process 23912 exists +0ms
                                  [100%]

==================================== ERRORS ====================================
______ ERROR at setup of test_serialization_deserialization[serialized6] _______

self = <websockets.legacy.client.Connect object at 0x7f16b1409510>

    async def __await_impl_timeout__(self) -> WebSocketClientProtocol:
        async with asyncio_timeout(self.open_timeout):
>           return await self.__await_impl__()

/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/websockets/legacy/client.py:655: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
```

**Comment by thiagowfx** [comment]
Confirmed it's still very flaky

**Comment by thiagowfx** [comment]
> could you please check why the tests are failing?

Closing this. The point of this PR was to confirm the E2E tests (ubuntu, headless) seem flakier with a more recent version of `browsers`.

**Pull request closed without merging**
