### PR TITLE
feat: export `MapperOptions` TS type

### PR DESCRIPTION
**Pull request by sadym-chromium**
Export `MapperOptions` type for being able to use from Puppeteer

### CODE REVIEW

**Review by OrKoN — APPROVED** [review]

**Comment by OrKoN** [comment]
Use the `automerge` label

**Comment by thiagowfx** [comment]
The GitHub PR title is independent from the commit message

**Comment by sadym-chromium** [comment]
> The GitHub PR title is independent from the commit message

I expected it to get the commit message from auto-commit. I guess I had to set `automerge` for that.

**Comment by OrKoN** [comment]
Screenshot 2023-11-21 at 15 23 43

your commit does not conform to the convention.

**Comment by OrKoN** [comment]
If you configure the message via GitHub UI for the PR, you need to use automerge label to indicate that you gonna provide a commit message via the automerge feature and disable the commit checks. It's recommended that you use conventional commits for the commits though.

**Pull request merged**
