### PR TITLE
test: re-baseline WPT expectations

### PR DESCRIPTION
**Pull request by sadym-chromium**
Step 1: remove all expectations and run CI.
Step 2: compare generated expectations with the actual one.

### CODE REVIEW

**Review by thiagowfx — APPROVED** [review]

**Comment by thiagowfx** [comment]
This is indeed useful to do sometimes, because the `wpt` CLI does not have the ability to remove old (e.g. renamed) expectations.

**Comment by thiagowfx** [comment]
Ideally we could have a monthly (or even weekly?) job that does what you're doing now. What do you think?

**Comment by sadym-chromium** [comment]
> Ideally we could have a monthly (or even weekly?) job that does what you're doing now. What do you think?

Agree! It would be nice to automate and run monthly

**Comment by sadym-chromium** [comment]
The PR can bring some flakiness. Postponing to the next week.

**Review by thiagowfx — APPROVED** [review]

**Comment by thiagowfx** [comment]
Merge?

**Comment by sadym-chromium** [comment]
Run CI again to verify it's stability

**Pull request merged**
