### PR TITLE
screenshots: update image golden data for E2E test for local runs

### PR DESCRIPTION
**Pull request by thiagowfx**
Bug: #547

### CODE REVIEW

**Comment by thiagowfx** [comment]
Now the test passes both locally and in CI :D

**Review by OrKoN — APPROVED** [review]

**Comment by OrKoN** [comment]
I have merged by accident :( feel free to revert if not ready

**Comment by thiagowfx** [comment]
Up to Maksim

**Comment by sadym-chromium** [comment]
I think we still have to find a way to test it regardless of platform. So event having the tests passing, I'd reopen the bug.

**Pull request merged**
