### PR TITLE
chore: remove some prefixes for website

### PR DESCRIPTION
**Pull request by Lightning00Blade**
Removes some `prefixes` in order to be more digestible and closer to the wpt.fyi dashboard that way it's easy to compare.
image

### CODE REVIEW

**Comment by thiagowfx** [comment]
The screenshot is not entirely correct:

- `logentry_added` -> `log/entry_added`
- `errorserrors.py` -> `errors/errors.py`

Removing prefixes is OK, but consider keeping at least the last directory name when the entry is terminal.

**Comment by thiagowfx** [comment]
There's a second disadvantage: We lose the ability to easily do copy + paste; we would need to write the whole path by hand.

This is not a blocker from my side, I'm happy to accept the PR, but let's at least fix the issue mentioned in the previous comment.

**Review by thiagowfx — CHANGES_REQUESTED** [review]
See comments in the PR

**Comment by Lightning00Blade** [comment]
I missed that its a regression for sure -  will fix. Can you give an example for what you are suggesting.
Also thinking about it it may be easy to have a button with toggle - default is short - toggle to long, how does that sound?

**Comment by thiagowfx** [comment]
>  Can you give an example for what you are suggesting.
> Also thinking about it it may be easy to have a button with toggle - default is short - toggle to long, how does that sound?

Hmm, for example:
image

I can easily copy and paste `/webdriver/tests/bidi/network/response_completed` to pass as an argument to `runWPTAll.sh` locally. With the short version, this is just `response_completed`, and one needs to write the full prefix manually.

That said, there's an alternative: We could augment the run WPT CLI tool to automatically prepend `/webdriver/tests/bidi` if it's not there. Then having the full prefix in the dashboard becomes unnecessary.

The toggle suggestion would work too.

I would say, let's try to go towards the simples route. :)

**Comment by mathiasbynens** [comment]
Happy to defer to @thiagowfx here. Thanks!

**Comment by Lightning00Blade** [comment]
image
image

**Pull request merged**
