### PR TITLE
fix: always provide url in `browsingContext.navigationStarted`

### PR DESCRIPTION
**Pull request by sadym-chromium**
Rely on `Page.frameRequestedNavigation` and `Page.frameScheduledNavigation`.

### CODE REVIEW

**Comment by OrKoN** [comment]
Before landing this let's discuss https://github.com/GoogleChromeLabs/chromium-bidi/issues/2415 If this lands, we probably won't be able to update chromium-bidi in Puppeteer until 129 is out.

**Comment by OrKoN** [comment]
blocked on https://github.com/GoogleChromeLabs/chromium-bidi/issues/2536 Could we mark it as a breaking change perhaps? until the roller is able to bump the versions

**Review by OrKoN — APPROVED** [review]

**Comment by OrKoN** [comment]
Note that the label alone would not mark it as a breaking change IIRC.

**Comment by sadym-chromium** [comment]
converted to draft to prevent accidental merge

**Review by OrKoN — APPROVED** [review]

**Pull request merged**
