### PR TITLE
Add `PROTO.binding` type to Local Value.

### PR DESCRIPTION
**Pull request by sadym-chromium**
https://github.com/GoogleChromeLabs/chromium-bidi/issues/79

Based on discussion https://github.com/w3c/webdriver-bidi/issues/157

> Instead of adding global bindings, pass bindings as deserializable arguments to `script.callFunction`. 
...
The argument can be something like:
> 
> ```
> {
>   type: "binding", 
>   value: "SOME_BINDING_NAME"
> }
> ```
> 
> , which will be deserialized to a callback. Calling that callback with any arguments will cause the BiDi event with those arguments like:
> 
> ```
> {
>   method: "script.bindingCalled",
>   params: {
>     arguments: [... remote values ...],
>     name: "SOME_BINDING_NAME"
>   }
> }
> ```

### CODE REVIEW

**Comment by sadym-chromium** [comment]
@bwalderman PTAL

**Comment by bwalderman** [comment]
@sadym-chromium, I'm sorry for the delay in reviewing this. I'd like to have a little more consensus on https://github.com/w3c/webdriver-bidi/issues/157 first. I'm about to be on vacation for a few days, but I will update that thread on Monday.

**Comment by sadym-chromium** [comment]
> @sadym-chromium, I'm sorry for the delay in reviewing this. I'd like to have a little more consensus on [w3c/webdriver-bidi#157](https://github.com/w3c/webdriver-bidi/issues/157) first. I'm about to be on vacation for a few days, but I will update that thread on Monday.

Prefix `PROTO` doesn't require us to support the functionality at all. It is there as an illustration of principe suggestion.

**Review by bwalderman — APPROVED** [review]

**Comment by bwalderman** [comment]
Approved. Sorry again for the long delay. From the issue discussion, it sounds like there's general agreement on the shape of the API, if not the name.

**Pull request merged**
