### PR TITLE
Make CDP implementation usable on both server and browser

### PR DESCRIPTION
**Pull request by bwalderman**
This change moves the CdpClient class and some related files from src/bidiMapper/utils/cdp to src/cdp. I've also moved files from src/bidiMapper/utils that cdp/ depends on. These are now under src/utils.

The end result is that code common to the server and mapper can be placed in src/ and both server and mapper code should be able to import it normally. This is to prepare to use the CdpClient class on the server side, and to help make the "standalone" configuration in #14 possible.

To get the build and unit tests working again after the move, I had to make some changes to the package.json and tsconfig files...

Rollup was having trouble recognizing mapper.ts as a typescript file and so would hit a syntax error when trying to build. I was able to solve this by removing the tsconfig.json file in src/bidiMapper. There is only one tsconfig.json file now (the one in src). This appears to let both the rollup build and server build work as expected. Having a single tsconfig should be okay because it enables code sharing and rollup will only pull in code that it actually needs.

There was also an issue due to the project being defined as an ESM module. Now that there is only one tsconfig, the unit tests files are being built with `"module": "ESNext"` like everything else. However, ts-node doesn't yet fully support ESM module loading (see https://github.com/TypeStrong/ts-node/issues/1007). I spent some time trying to get mocha to run with ts-node's experimental ESM support but I wasn't able to find a quick solution. Instead, I removed the `"type": "module"` property from the project's package.json and set the tsconfig to output "commonjs" modules. This lets the mocha unit tests and the actual product work as expected. Using "commonjs" as the target for Node projects appears to be recommended anyway: https://github.com/tsconfig/bases/blob/main/bases/node16.json

### CODE REVIEW

**Comment by bwalderman** [comment]
This change means we can probably revert #27 but I left that out to keep this PR smaller.

**Review by sadym-chromium — COMMENTED** [review]
In general I like the idea of #14. But I would keep the mapper logic as independent as possible, as in future we would need to have the mapper JS code in ChromeDriver to implement the magic with running mapper in Chrome.

**Comment by bwalderman** [comment]
@sadym-chromium agreed, the mapper logic should be always buildable as an independent target. As long as we only share code that will work in both node.js and browser environments then this should be fine.

**Comment by sadym-chromium** [comment]
ok, let's make it

**Review by sadym-chromium — APPROVED** [review]
Ok, let's go this way for now, and will think how to inject it into ChromeDriver later

**Comment by bwalderman** [comment]
@sadym-chromium thanks for the signoff. The mapper does still build as an single injectable file even with this PR. That aspect hasn't change.

**Pull request merged**
