### PR TITLE
Document how to run WPT tests with locally built chromedriver/mapper

### PR DESCRIPTION
**Pull request by thiagowfx**

### CODE REVIEW

**Comment by sadym-chromium** [comment]
Let's wait for the [4216 - Run ChromeDriver with custom BiDiMapper - chromedriver](https://crbug.com/chromedriver/4216) t obe implemented, and document running Mapper via ChromeDriver with the CLI argument.

**Comment by thiagowfx** [comment]
@sadym-chromium given https://chromium.googlesource.com/chromium/src/+/35bf95d2a3d2b540ddccf1dc96ba00da24f10338, should we close this?

Some parts of it still seem applicable, what do you think?

**Comment by thiagowfx** [comment]
Updated to account for https://chromium.googlesource.com/chromium/src/+/35bf95d2a3d2b540ddccf1dc96ba00da24f10338, documented the newly added flag switch.

**Review by sadym-chromium — COMMENTED** [review]
LGTM

**Pull request merged**
