### PR TITLE
chore: rename folder from `domains` to `modules`

### PR DESCRIPTION
**Pull request by Lightning00Blade**
`domains` is the CDP separation but BiDi uses `modules` give this and the fact we split them based on the BiDi implementation we should rename if for consistency.

### CODE REVIEW

**Comment by OrKoN** [comment]
Would you mind delaying renaming this until we have no in-flight PRs including domains?

**Comment by OrKoN** [comment]
You would also need to update all imports :)

**Comment by Lightning00Blade** [comment]
Yeah, but I forgot to push the second commit, having the rename in one and the change in another make it (more likely) the file to keep its history.
What is the PR that are inflight? That we think we will merge in the coming days?

**Comment by OrKoN** [comment]
The bluetooth stuff, it will probably take longer.

**Comment by Lightning00Blade** [comment]
Happy to rebase it myself after this lands.

**Review by OrKoN — APPROVED** [review]

**Pull request merged**
