### PR TITLE
ci: gather all WPT tests to generate report

### PR DESCRIPTION
**Pull request by sadym-chromium**
When generating WPT test report, get all the tests from the WPT, and update the status of those actually run. This allows to get detailed information about skipped tests and gather more detailed data on the passing rate.

If the approach is accepted, the WPT path should be passed in parameters.

Experimental run: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/8174790184

### CODE REVIEW

**Comment by Lightning00Blade** [comment]
@sadym-chromium The run is failing due to no `pytest` being found.

**Comment by Lightning00Blade** [comment]
@sadym-chromium Run still fails due to not correct set-up.

**Comment by sadym-chromium** [comment]
> @sadym-chromium Run still fails due to not correct set-up.

I know, WIP

**Comment by sadym-chromium** [comment]
Closing, in favor of removing skips from the expectations at all

**Pull request closed without merging**
