### PR TITLE
feat: allow Chrome-specific params in user contexts

### PR DESCRIPTION
**Pull request by OrKoN**
The proxy servers are somewhat difficult to test. Does the pytest server support a proxy mode? Any test suggestions for vendor specific attributes?

### CODE REVIEW

**Comment by OrKoN** [comment]
@sadym-chromium do you have an advice for on how to test this best?

**Comment by sadym-chromium** [comment]
> @sadym-chromium do you have an advice for on how to test this best?

We can implement the proxy along with our http server in pytest: https://stackoverflow.com/a/4412630/22971202

**Comment by OrKoN** [comment]
@sadym-chromium it does not look like this is a correct implementation of the proxy. Also https://github.com/csernazs/pytest-httpserver/issues/39 is not available yet.

**Comment by OrKoN** [comment]
I will look into making a werkzeug proxy.

**Comment by OrKoN** [comment]
Alright it does not seem to work as expected

**Comment by OrKoN** [comment]
I suggest that we test it via Puppeteer that has a flexible proxy server. WDYT?

**Pull request closed without merging**
