### PR TITLE
chore: remove deps for Args parsing

### PR DESCRIPTION
**Pull request by Lightning00Blade**

### CODE REVIEW

**Comment by sadym-chromium** [comment]
Please make sure you update all the usages, eg in [tools/run-bidi-server.mjs](https://github.com/GoogleChromeLabs/chromium-bidi/blob/82d13df43b04e5e31118e21d1b6ba13bce9eb87c/tools/run-bidi-server.mjs#L81).

**Comment by Lightning00Blade** [comment]
That should be update here - https://github.com/GoogleChromeLabs/chromium-bidi/pull/1663/files#diff-06b8a2692cf19ff55e4aa295e81ac271dcd639e3149221ce9f8e6b6f18f71411R87

**Comment by sadym-chromium** [comment]
> That should be update here - https://github.com/GoogleChromeLabs/chromium-bidi/pull/1663/files#diff-06b8a2692cf19ff55e4aa295e81ac271dcd639e3149221ce9f8e6b6f18f71411R87

e2e headless CI job runs tests in headful mode now.

**Comment by Lightning00Blade** [comment]
I think instead of using the build in Node, we should use only `yargs` as we use it in multiple places and allows for faster development.

**Pull request closed without merging**
