### PR TITLE
ci: add Puppeteer label

### PR DESCRIPTION
**Pull request by Lightning00Blade**
Similar to the Devtools one we created we should have one for Puppeteer here.

### CODE REVIEW

**Review by jrandolf — APPROVED** [review]

**Comment by jrandolf** [comment]
Nice!

**Comment by thiagowfx** [comment]
Does this mean that if we add the puppeteer label to a PR then it will run the puppeteer test suite?

If so: That's cool!

**Comment by sadym-chromium** [comment]
Would you mind to update the readme, or add more details to this CI step explaining what does it do and how to use it?

**Comment by Lightning00Blade** [comment]
Create #1330 to address that.

**Pull request merged**
