### PR TITLE
test: introduce pytest flaky plug-in, mark observed flakes

### PR DESCRIPTION
**Pull request by thiagowfx**
Docs: https://pypi.org/project/flaky/

### CODE REVIEW

**Comment by thiagowfx** [comment]
Input is flaky, e.g. https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/5645309009/job/15290822776?pr=1082

**Comment by thiagowfx** [comment]
More flakes: https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/5645678909/job/15291959888?pr=1085

**Comment by thiagowfx** [comment]
@jrandolf thoughts?

**Comment by jrandolf** [comment]
This flakiness is due to headful mode. It'd be better to disable these tests in headful rather than marking them as flaky.

**Comment by thiagowfx** [comment]
Would you like to follow up with a PR?

**Comment by thiagowfx** [comment]
@jrandolf what is your take on this PR? The input tests are still flaky. If you have any other suggestions on how to tackle that, we could do so. Didn't you once mention they were only flaky in headful?

**Comment by thiagowfx** [comment]
I am going to close this, but it can be reused as a reference in the future in case we have flaky E2E tests again.

**Pull request closed without merging**
