### PR TITLE
Release 0.4.4

### PR DESCRIPTION
**Pull request by OrKoN**

### CODE REVIEW

**Review by sadym-chromium — APPROVED** [review]

**Comment by mathiasbynens** [comment]
The release process is: https://github.com/GoogleChromeLabs/chromium-bidi#publish-new-npm-release i.e. this should happen on the `main` branch directly.

**Comment by mathiasbynens** [comment]
I’ve manually tagged `v0.4.4` and pushed it this time, so this version should be `npm publish`ed soon.

**Comment by thiagowfx** [comment]
Should we remove `0.4.3` from Releases? https://github.com/GoogleChromeLabs/chromium-bidi/releases

AFAIK we only care about tags for this process.

**Comment by OrKoN** [comment]
Hm, we need to update the process (it does not work with code review practices and branch protection). I like seeing the release on the GitHub pages and now we are missing a release there. Let me open a proposal for it.

I was at a dentist and could not respond on time...

**Pull request merged**
